{
 "title": "Kubernetes Logs Dashboard",
 "tags": [
  "kubernetes",
  "loki",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "query": "label_values(pod, namespace=\"$namespace\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Logs - Real-time",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"application\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "All Namespaces Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=~\".+\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Nginx Pod Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"application\", app=\"nginx\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{namespace=~\".+\"} |= \"error\" | logfmt",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Log Volume by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Log Lines" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\".+\"}[1m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Log Volume by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Log Lines" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"application\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}